### ISSUE TITLE
[IDEA/REQUEST] Toggle Left Sidebar Pin on Android

### ISSUE THREAD

**Issue by the0s0ph1st** [jdanielmourao/obsidian-sanctum#116]
**Is your feature request related to a problem? Please describe.**

Sanctum has been my workhorse theme for managing a lot of things on Obsidian when on my phone or tablet. I have wondered though why the right sidebar pin toggle is visible while the left sidebar one is not. It is not much of a problem if I am using my phone, but it is troublesome when using my tablet, where it is better to have the option to keep both sidebars open.

**Describe the solution you'd like**
A way to toggle the left sidebar pin on and off.

**Describe alternatives you've considered**
The main workaround right now that I have been doing is changing the theme to Default Obsidian and toggling the left sidebar pin then going back to Sanctum. If I know how to script I probably would have found a better way to do that but alas I do not.

**Comment by jdanielmourao** [comment]
Hi! The left sidebar pin isn't present in mobile Sanctum because I decided to strip away the container/element it is a part of. It would look strange to have a huge space on top of the sidebar with just a small pin to the right (like it is when it's already pinned, except the message I left there). It will stay like that until I find a better solution. I have an idea for it, but am yet to test it out properly.

**Comment by jdanielmourao** [comment]
As of version 0.6.3, there is now a pin in the left sidebar
