### ISSUE TITLE
[IDEA/REQUEST] Add a SS option for new link

### ISSUE THREAD

**Issue by Mara-Li** [jdanielmourao/obsidian-sanctum#127]
**Is your feature request related to a problem? Please describe.**

The new update broke completely my snippet for supercharged link. I don't know how I can revert and use the old behavior to style some of my links.

I also don't like some styling.

**Describe the solution you'd like**

For me, the best is to simply add an option to use the new links style or not in SS.

**Describe alternatives you've considered**

**Comment by arthursoares** [comment]
I second this. I'm not sure about the new link style as well. IMHO, It draws too much attention and disrupts the reading flow. I would favor something comparable to the `#tag` rendering with an addition to the `css:after` icon of the external link.

```markdown
- Here is a #tag
- Here is an [External Link](hello.com)
- Here is an [[Internal Link]]
- Here is an URL that renders as a link https://openprocessing.org/sketch/1413816
```


- Here is a #tag
- Here is an [External Link](hello.com)
- Here is an [[Internal Link]]
- Here is an URL that renders as a link https://openprocessing.org/sketch/1413816

<img width="778" alt="Capture 2022-01-26 14 43 17" src="https://user-images.githubusercontent.com/533339/151173784-5e9fbfcb-bb86-4744-82cc-971f1433a7cf.png">

<img width="733" alt="Capture 2022-01-26 14 43 20" src="https://user-images.githubusercontent.com/533339/151173798-2b40bb9f-4942-4f3d-989a-87521a884cf2.png">

**Comment by jdanielmourao** [comment]
> I second this. I'm not sure about the new link style as well. IMHO, It draws too much attention and disrupts the reading flow. I would favor something comparable to the `#tag` rendering with an addition to the `css:after` icon of the external link.

There is a link image, it doesn't show on your aliased external link example because aliased external links require `https://` at the beginning of the link in order to be recognized as external links. If you hover it, it should probably tell you it's in fact an unresolved internal link, hence the same styling.

I'm thinking about adding a toggle for a more “understated” link, which will most likely work like the bare external links: regular formatted text with accent colour, and the regular background colour on hover.
