### ISSUE TITLE
[BUG] making text ***like this*** (Bold and italic) make it highlighted

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#139]
**Describe the bug**
Making text bold and italic make it ==like this==

**To Reproduce**
1. make `***`text`***`
2. Go in preview mode (or use live preview)
3. See the text

**Expected behavior**
The bold and italic should make the text bold and italic

**Screenshots**
![image](https://user-images.githubusercontent.com/79509045/152673046-bee98bbc-3716-4fa6-a23c-fe684674eebc.png)

**Version [Desktop or Mobile]:**
PC (Linux, AUR version)

**Editor**
New CM6

**Additional context**
The color is not the same

**Comment by jdanielmourao** [comment]
I somehow forgot to post an answer, even though I had read it. This was an intentional decision, rather than use bold italic, the theme styles it as an `ins` type of styling. You can use it to highlight recent additions to notes (as opposed to the cssClass `redacted` which styles strike-throughs in red highlight, so as to highlight removed text.

**Comment by TRENEEDANAME** [comment]
Ok
