### ISSUE TITLE
Feature Request/Bugfix: Icon Folder compatibility

### ISSUE THREAD

**Issue by Relkion** [jdanielmourao/obsidian-sanctum#150]
Using [Obsidian Icon Folder](https://github.com/FlorianWoelki/obsidian-icon-folder) doesn't replace the existing icon but adds addition icon next to folders/files. I realize there is an option to disable the default icons, but it would be nice to have both default set and additional icons for special items.

<img width="169" alt="Screen Shot 2022-03-16 at 7 44 56 PM" src="https://user-images.githubusercontent.com/101229519/158726370-9bac753a-14a7-442c-9337-210c7498be34.png">

**Comment by jdanielmourao** [comment]
Hi! Obsidian Icon Folder being a plugin, it adds a custom class in order to place an icon before any folder. This method is not possible in native obsidian, hence why I use a different CSS trick to achieve the same result. 
If you're hoping for more compatibility besides my Style Settings option to disable icons, I'd advise you to submit a feature request on Obsidian Icon Folder's repository. Sanctum being a simple theme, there's only so much one can achieve with CSS only, and plugins having quite a bit more options, it might be possible for the developer to disable `::before` CSS pseudo-elements of a specific folder, if that folder has a custom icon. Hope that makes sense!
Having said this, although I can't do much on my end regarding the theme, there are ways you can target specific icons with CSS snippets, in case you have the patience for it. Here's an example CSS snippet that should work:

```
.nav-folder-title[data-path='FOLDER-NAME'] .nav-folder-title-content::before {
	display: none;
}
```

Again, if you're hoping for a more user-friendly or streamlined way, the only option I see is through the plugin itself.
