### ISSUE TITLE
[BUG] Small conflicting with Outliner's fold 

### ISSUE THREAD

**Issue by b1uegh0st** [jdanielmourao/obsidian-sanctum#28]
**Describe the bug**
The folded bullet's `...` is not placed right:
- In Edit mode, it is too close to the text (see the picture)
- In Preview mode, it just creates a separate line with 3 dots. (see second picture, also a comparison for header's folding which is okay).

**To Reproduce**
- I use the Outliner plugin a lot. In this plug-in, I do **not** use the setting "Improve the style of your lists" - which interferes with the CSS more.
- Just create a bullet point and some sub-level bullet point, then fold up.
- I think this simply some problem with handling the space when the bullet is fold.

**Expected behavior**
The three dots will be spaced out like in Preview for Headers fold.

**Screenshots**
![image](https://user-images.githubusercontent.com/6695697/140551095-9a0dc73e-17a2-4a73-9382-f5663f9a9c2b.png)
![image](https://user-images.githubusercontent.com/6695697/140551459-0c29caeb-a2e7-41d1-be08-c5def6ae4a0a.png)

**Version [Desktop or Mobile]:**
Desktop

**Additional context**
Thanks for the great theme.

**Comment by b1uegh0st** [comment]
On a slightly related notes, I want to confirm when you say the theme is built for IBM Plex, this is what you have in mind (I also your font-carrying css file and enabled it).

![image](https://user-images.githubusercontent.com/6695697/140554944-fcd91022-7c35-4935-a504-e89cff0814a1.png)

I want to ask because when I revert all of this to default the the folding three-dots is okay again.

**Comment by jdanielmourao** [comment]
Hi! The fold indicator css is currently setup for the font that comes with the theme - iA Writer. Since I recommend IBM Plex, I've also included a snippet in this repository named 'fold_indicator', which you can edit in order to match IBM Plex (it's dependant on the font's default width. For IBM plex, I'd recommend changing the `margin-left` value to `-0.5rem`, and that should fix it ;) I'll probably make that clearer in the documentation, as well as the snippet itself.

**Comment by b1uegh0st** [comment]
Hi, 
 
 Thanks for the clarification. I would like to 1. Continue to report on the bug and 2. Make a suggestion.

 1. Having the snippets on at `-0.5rem` fix the 3 dots in Editing mode. In **Preview mode** it still results in a separate line.
  
![image](https://user-images.githubusercontent.com/6695697/140648831-659f2fe1-4b08-4988-91c3-33ae9ccf8dd2.png)
 
 2. As per the suggestion for the **IBM Plex support** (great font, thanks for the suggestion):
  - I think it can be helpful if packed separately in a CSS snippets (so split the IBM fonts and pack it with the adjustments that goes with it). In that case, the fonts settings in Style Settings can be made with the IBM fonts at top priority, then IA Writer. By default if users don't download the IBM Plex CSS then they get the IA look.
  - The other approach which likely takes a bit more work (and thoughts ahead of how to structure) is that this switch becomes a Style Settings variable ("tick this and you will move to IBM Plex mode"). That may conflict a bit with the flexibility you want to provide people to choose the fonts they want to use. But it will strongly preserve the look you want for the theme (which is highly opinionated anyway, and that is not a bad thing).

**Comment by jdanielmourao** [comment]
Hi again! I think the issue with preview mode might be related to "loose" lists, that is, a list that has at least 1 space/paragraph between points. At least that's how I got that same effect. I could try to remove that "loose" list feature altogether with css, but will have to look into it.
As for the suggestions, thank you very much! Both make a lot of sense, and I'll probably implement the 1st one in the near future. Like you also suspected, making an "IBM Plex mode" could have some implications with Style Settings, but I think that if I make a custom class for it, it can overwrite them. 🤔 Even if it worked, though it would be still be dependant on people adding the font separately, since it'd make the theme file way too heavy (like almost 2MB heavier). As a toggle, though, I think it could still work.
Do get back to me on the list issue when you can 😉

**Comment by b1uegh0st** [comment]
You are right about the "loose list". Funnily it's exactly that file constantly use to showcase the problem that has it.

Reproduce:
- All three `...` has problem.
- Delete the blank line (in the picture under).
- All the other `...` works.
- (so it does affect the whole parent and "neighboring list").

Thanks for pointing it out. It is indeed a rare exception. You should not prioritize it. 

![image](https://user-images.githubusercontent.com/6695697/140762231-a1e4fe0b-c560-46f7-a93c-95a03658785b.png)

As per the other topic, here is my temporary choice ^^ will need to update them manually though.
![image](https://user-images.githubusercontent.com/6695697/140762789-66e128dc-62c8-4447-9369-cd36828c4dea.png)

Last not least, thanks for theme and pointing us towards the font (and hence its story). Find many interesting things digging down that (nerdy) rabbit hole.
