### ISSUE TITLE
Modified colors for headings are not visible

### ISSUE THREAD

**Issue by ih8snow** [jdanielmourao/obsidian-sanctum#41]
Hi,

I modified the Heading Colory via "Style Settings", but actually I don't see the colors in edit/preview mode.
Restarted Obsidian, but still the black headings instead of my colors.

Any idea what I did wrong here?

/ Jörn

Thnaks for this great Theme! Just send you a ko-fi :-)

{
  "sanctum@@font-preview": "proxima-nova, sans-serif",
  "sanctum@@font-editor": "proxima-nova, sans-serif",
  "sanctum@@font-ui": "proxima-nova, sans-serif",
  "sanctum@@font-mono": "proxima-nova, sans-serif",
  "sanctum@@font-heading-preview": "proxima-nova, sans-serif",
  "sanctum@@font-heading-editor": "proxima-nova, sans-serif",
  "sanctum@@heading-2": 88,
  "sanctum@@heading-clr": true,
  "sanctum@@heading-clr-bg": true,
  "sanctum@@color-heading-1@@dark": "#182D48",
  "sanctum@@color-heading-1@@light": "#182D48",
  "sanctum@@color-heading-2@@dark": "#1A3154",
  "sanctum@@color-heading-2@@light": "#1A3154",
  "sanctum@@color-heading-3@@dark": "#4B5A73",
  "sanctum@@color-heading-3@@light": "#4B5A73",
  "sanctum@@color-heading-4@@dark": "#99A0AB",
  "sanctum@@color-heading-4@@light": "#99A0AB"
}

**Comment by jdanielmourao** [comment]
Hi! Currently I'm not too happy with the heading color style settings setup, because it's unintuitive. 
So here's how to do it:
1. You go to the Style Settings and find the Heading Font Color option.
2. You toggle "Toggle Heading Font Colours"
<img width="583" alt="Loom_6Iy1hJyii6" src="https://user-images.githubusercontent.com/91087143/141653652-5d45f839-0913-4fd2-a9e4-2026f0844504.png">

3. You select which heading and mode (light or dark) you want to edit:
<img width="560" alt="Loom_8IlVJx2wSr" src="https://user-images.githubusercontent.com/91087143/141653748-d23cee5e-3729-44c2-8e06-88f1fe7c8756.png">

4. You click the one you want, change it to your liking, and click "Save"
<img width="212" alt="Loom_2x5rz6gxT3" src="https://user-images.githubusercontent.com/91087143/141653779-50990d44-81dc-4e54-8949-c86b91ffc50c.png">

That should do it! I'll probably just add a color palette people can choose from in the future, so it's easier to deal with.

**Comment by ih8snow** [comment]
Hi,
I followed your instructions, all great!

Just one  more question:
I don't like the switch in font when I go from edit to preview:
![font](https://user-images.githubusercontent.com/82544852/141658321-233c1c32-5e39-4fa4-8030-9805fb27bdec.jpg)
:
How can I switch that off?

**Comment by jdanielmourao** [comment]
Go to `Style Settings` -> `Typography` -> `Headings` -> `Heading Font Editor Mode` and click the icon at the right that says "Restore default" when hovered.

**Comment by ih8snow** [comment]
👍
