### ISSUE TITLE
[BUG] The quote feature disappear in Live mode

### ISSUE THREAD

**Issue by TRENEEDANAME** [jdanielmourao/obsidian-sanctum#78]
**Describe the bug**
The quote disappears, it would be nice if you add the same little "quote drawing", because it makes it impossible to differentiate quote and normal text.
If you do :
> <cite>This is a citation</cite>
The citation is good

**Expected behavior**
Have the same blue/green quote symbol

**Screenshots**

#### Live Mode : preview
![image](https://user-images.githubusercontent.com/79509045/147213158-856d7066-0ee0-4392-93d7-f7804cb3c69e.png)

#### Live Mode : edit
![image](https://user-images.githubusercontent.com/79509045/147213229-24ef6c59-7d31-4b44-962a-b3d37d9c52d6.png)

#### Expected
![image](https://user-images.githubusercontent.com/79509045/147213327-901341c5-d165-44b2-8b75-9a19730f8406.png)

Maybe with only the little quote

**Version [Desktop or Mobile]:**
Desktop (Linux version)

**Additional context**
None

**Comment by jdanielmourao** [comment]
Hi! For as long as Live Preview has been in insider testing, I've been trying to get quotes to work. It didn't allow for that kind of customization because of a few technical issues I could not get past, and were hard coded into the default app, but with the most recent update (which was the general release), it is now possible to do so, and I've managed to make something like what you've suggested. It will be released in the next update, which hopefully will come out before christmas. 🤞🏻

**Comment by jdanielmourao** [comment]
Just release a new update. Check it out! :)
