### ISSUE TITLE
Commands to open/close the left and right side bars

### ISSUE THREAD

**Issue by thephm** [jdanielmourao/obsidian-sanctum#79]
**Is your feature request related to a problem? Please describe.**
I need a quick way to hide and show the sidebars without using my mouse, it's somewhat related to https://github.com/jdanielmourao/obsidian-sanctum/issues/71#issuecomment-999669463

**Describe the solution you'd like**
Do something similar to what Jira does and have a keyboard shortcut to close/open the left sidebar using Ctrl+[ but instead of using a different combo to close it, use the same key combo, ie. pressing Ctrl+[ opens/closes ... Then, use Ctrl + ] to open/close the right sidebar 

**Describe alternatives you've considered**
I was thinking to make this an extension on my own but just too many projects active right now and I need to start finishing those and stop starting new ones!

**Additional context**
None.

**Comment by jdanielmourao** [comment]
I don't think you need to create an alternative, since there are already 2 hotkeys which you can set to toggle the sidebars on and off. Simply go to the Hotkeys Menu in Settings, and search "sidebar". You'll then need to assign a hotkey to them.
![image](https://user-images.githubusercontent.com/91087143/147340192-dd1f4b95-1961-4bfc-8ab0-2e2ff07e80c8.png)
